/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: c:\Users\Olli\Documents\GitHub\ardupilot\modules\uavcan\dsdl\uavcan\olliw\storm32\28300.Control.uavcan
 */

#ifndef UAVCAN_OLLIW_STORM32_CONTROL_HPP_INCLUDED
#define UAVCAN_OLLIW_STORM32_CONTROL_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Gimbal Control
#
# aeronautical frame, NED (right-handed, X-front, Y-right, Z-down)
#
# The gimbal can be controlled in four ways:
# A) Specifcation of the gimbal angles only.
#    In this case do not specify the angular rates, or set them to NAN.
#    The frame field will be ignored, and the angles will be interpreted as natural gimbal angles.
#    As a consequence, it is up to the sender of the message to ensure that proper angles are sent.
# B) Specifcation of the gimbal orientation quaternion only.
#    In this case do not specify the angular rates, or set them to NAN.
#    The quaternion will be interpreted as specified in the frame field.
# C) Specifcation of the gimbal angular rates only.
#    In this case set the angles/quaternion to NAN.
#    The angular rates will be interpreted as specified in the frame field.
# D) Specifcation of the gimbal orientation quaternion and angular rates.
#    The quaternion and angular rates will be interpreted as specified in the frame field.
#
# Any gimbal is required to support A), and B) with frame = 1. All other combinatons are
# optional. If a gimbal doesn't support a combination, the mode field should be respected,
# but all other fields should be ignored by the gimbal. It is up to the sender of the
# message to ensure that proper data are sent.
#
# Notes:
# 1) The gimbal orientation is usually expressed neither in a body nor fixed frame.
# This is so because a gimbal usally doesn't know about the absolute heading, but only
# about its heading in reference to the vehicle. Thus the natural quantities to express
# the gimbal orientation is using roll and pitch in the fixed frame, and a yaw in relation
# to the body frame. Only if the absolute heading of the vehicle is known to the gimbal,
# it can handle orientations in the fixed frame.
# 2) Most 3-axis gimbals use a pitch-roll-yaw arrangement, corresponding to 312 Euler
# angles. The gimbal angles do thus not correspond to the 321-Euler angles usually used
# in aeronautics, and the latter would in fact be useless for gimbal control.
#
# mode = 0 means that the mode should not be changed
#
# frame = 0 means the "natural" quaternion frame of a 3-axis gimbal
# frame = 0x7F means that no frame is specified, and that only the mode field should be considered
#

uint8 gimbal_id                 #0 means broadcast, any gimbal should listen

uint8 mode                      #0 means that the mode should not be changed

uint8 control_mode              #specifies the meaning of the data

float32[4] orientation          #the meaning of the content is defined by frame, angles: roll, pitch, yaw in rad, otherwise: orientation quaternion in xyzw

float32[<=3] angular_velocity   #roll, pitch, yaw rates in rad/s
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.olliw.storm32.Control
saturated uint8 gimbal_id
saturated uint8 mode
saturated uint8 control_mode
saturated float32[4] orientation
saturated float32[<=3] angular_velocity
******************************************************************************/

#undef gimbal_id
#undef mode
#undef control_mode
#undef orientation
#undef angular_velocity

namespace uavcan
{
namespace olliw
{
namespace storm32
{

template <int _tmpl>
struct UAVCAN_EXPORT Control_
{
    typedef const Control_<_tmpl>& ParameterType;
    typedef Control_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > gimbal_id;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > mode;
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > control_mode;
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeStatic, 4 > orientation;
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeDynamic, 3 > angular_velocity;
    };

    enum
    {
        MinBitLen
            = FieldTypes::gimbal_id::MinBitLen
            + FieldTypes::mode::MinBitLen
            + FieldTypes::control_mode::MinBitLen
            + FieldTypes::orientation::MinBitLen
            + FieldTypes::angular_velocity::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::gimbal_id::MaxBitLen
            + FieldTypes::mode::MaxBitLen
            + FieldTypes::control_mode::MaxBitLen
            + FieldTypes::orientation::MaxBitLen
            + FieldTypes::angular_velocity::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::gimbal_id >::Type gimbal_id;
    typename ::uavcan::StorageType< typename FieldTypes::mode >::Type mode;
    typename ::uavcan::StorageType< typename FieldTypes::control_mode >::Type control_mode;
    typename ::uavcan::StorageType< typename FieldTypes::orientation >::Type orientation;
    typename ::uavcan::StorageType< typename FieldTypes::angular_velocity >::Type angular_velocity;

    Control_()
        : gimbal_id()
        , mode()
        , control_mode()
        , orientation()
        , angular_velocity()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<250 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 28300 };

    static const char* getDataTypeFullName()
    {
        return "uavcan.olliw.storm32.Control";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Control_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        gimbal_id == rhs.gimbal_id &&
        mode == rhs.mode &&
        control_mode == rhs.control_mode &&
        orientation == rhs.orientation &&
        angular_velocity == rhs.angular_velocity;
}

template <int _tmpl>
bool Control_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(gimbal_id, rhs.gimbal_id) &&
        ::uavcan::areClose(mode, rhs.mode) &&
        ::uavcan::areClose(control_mode, rhs.control_mode) &&
        ::uavcan::areClose(orientation, rhs.orientation) &&
        ::uavcan::areClose(angular_velocity, rhs.angular_velocity);
}

template <int _tmpl>
int Control_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::gimbal_id::encode(self.gimbal_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::mode::encode(self.mode, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::control_mode::encode(self.control_mode, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::orientation::encode(self.orientation, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::angular_velocity::encode(self.angular_velocity, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Control_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::gimbal_id::decode(self.gimbal_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::mode::decode(self.mode, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::control_mode::decode(self.control_mode, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::orientation::decode(self.orientation, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::angular_velocity::decode(self.angular_velocity, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Control_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xBF15FB6305CE5599ULL);

    FieldTypes::gimbal_id::extendDataTypeSignature(signature);
    FieldTypes::mode::extendDataTypeSignature(signature);
    FieldTypes::control_mode::extendDataTypeSignature(signature);
    FieldTypes::orientation::extendDataTypeSignature(signature);
    FieldTypes::angular_velocity::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Control_<0> Control;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::uavcan::olliw::storm32::Control > _uavcan_gdtr_registrator_Control;

}

} // Namespace storm32
} // Namespace olliw
} // Namespace uavcan

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::uavcan::olliw::storm32::Control >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::uavcan::olliw::storm32::Control::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::uavcan::olliw::storm32::Control >::stream(Stream& s, ::uavcan::olliw::storm32::Control::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "gimbal_id: ";
    YamlStreamer< ::uavcan::olliw::storm32::Control::FieldTypes::gimbal_id >::stream(s, obj.gimbal_id, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "mode: ";
    YamlStreamer< ::uavcan::olliw::storm32::Control::FieldTypes::mode >::stream(s, obj.mode, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "control_mode: ";
    YamlStreamer< ::uavcan::olliw::storm32::Control::FieldTypes::control_mode >::stream(s, obj.control_mode, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "orientation: ";
    YamlStreamer< ::uavcan::olliw::storm32::Control::FieldTypes::orientation >::stream(s, obj.orientation, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "angular_velocity: ";
    YamlStreamer< ::uavcan::olliw::storm32::Control::FieldTypes::angular_velocity >::stream(s, obj.angular_velocity, level + 1);
}

}

namespace uavcan
{
namespace olliw
{
namespace storm32
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::uavcan::olliw::storm32::Control::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::uavcan::olliw::storm32::Control >::stream(s, obj, 0);
    return s;
}

} // Namespace storm32
} // Namespace olliw
} // Namespace uavcan

#endif // UAVCAN_OLLIW_STORM32_CONTROL_HPP_INCLUDED